package jp.personal.tasken.companion

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data class TokenColorReference(val token: String, val hex: String)

object TaskenMaterialColorTokens {
    val light = mapOf(
        "primary" to TokenColorReference("accent", "#8A2F3B"),
        "onPrimary" to TokenColorReference("onAccent", "#FFFFFF"),
        "primaryContainer" to TokenColorReference("accentSubtleBg", "#FBF3F4"),
        "onPrimaryContainer" to TokenColorReference("accentStrong", "#5E1F28"),
        "inversePrimary" to TokenColorReference("accentHover", "#73262F"),
        "secondary" to TokenColorReference("textSecondary", "#7C746E"),
        "onSecondary" to TokenColorReference("onAccent", "#FFFFFF"),
        "secondaryContainer" to TokenColorReference("surfaceMuted", "#EFE7E5"),
        "onSecondaryContainer" to TokenColorReference("text", "#26201E"),
        "tertiary" to TokenColorReference("info", "#2D7FB8"),
        "onTertiary" to TokenColorReference("onAccent", "#FFFFFF"),
        "tertiaryContainer" to TokenColorReference("infoBg", "#E8F1F8"),
        "onTertiaryContainer" to TokenColorReference("infoStrong", "#1C557D"),
        "background" to TokenColorReference("bg", "#F4EEEC"),
        "surface" to TokenColorReference("surface", "#FFFFFF"),
        "surfaceVariant" to TokenColorReference("surfaceSubtle", "#F9F4F4"),
        "surfaceTint" to TokenColorReference("accent", "#8A2F3B"),
        "inverseSurface" to TokenColorReference("text", "#26201E"),
        "inverseOnSurface" to TokenColorReference("surface", "#FFFFFF"),
        "outline" to TokenColorReference("border", "#DCC1C4"),
        "outlineVariant" to TokenColorReference("borderSubtle", "#ECE0DE"),
        "scrim" to TokenColorReference("bg", "#F4EEEC"),
        "onBackground" to TokenColorReference("text", "#26201E"),
        "onSurface" to TokenColorReference("text", "#26201E"),
        "onSurfaceVariant" to TokenColorReference("textSecondary", "#7C746E"),
        "error" to TokenColorReference("danger", "#CE3B3B"),
        "onError" to TokenColorReference("onAccent", "#FFFFFF"),
        "errorContainer" to TokenColorReference("dangerBg", "#FBEAEA"),
        "onErrorContainer" to TokenColorReference("dangerStrong", "#A12626"),
        "surfaceBright" to TokenColorReference("surface", "#FFFFFF"),
        "surfaceDim" to TokenColorReference("surfaceMuted", "#EFE7E5"),
        "surfaceContainer" to TokenColorReference("surfaceSubtle", "#F9F4F4"),
        "surfaceContainerHigh" to TokenColorReference("surfaceMuted", "#EFE7E5"),
        "surfaceContainerHighest" to TokenColorReference("borderSubtle", "#ECE0DE"),
        "surfaceContainerLow" to TokenColorReference("accentSubtleBg", "#FBF3F4"),
        "surfaceContainerLowest" to TokenColorReference("surface", "#FFFFFF"),
        "primaryFixed" to TokenColorReference("accentSubtleBg", "#FBF3F4"),
        "primaryFixedDim" to TokenColorReference("accentSubtleBd", "#E6BCC1"),
        "onPrimaryFixed" to TokenColorReference("text", "#26201E"),
        "onPrimaryFixedVariant" to TokenColorReference("accentStrong", "#5E1F28"),
        "secondaryFixed" to TokenColorReference("surfaceMuted", "#EFE7E5"),
        "secondaryFixedDim" to TokenColorReference("border", "#DCC1C4"),
        "onSecondaryFixed" to TokenColorReference("text", "#26201E"),
        "onSecondaryFixedVariant" to TokenColorReference("textSecondary", "#7C746E"),
        "tertiaryFixed" to TokenColorReference("infoBg", "#E8F1F8"),
        "tertiaryFixedDim" to TokenColorReference("infoBd", "#C3DCEE"),
        "onTertiaryFixed" to TokenColorReference("text", "#26201E"),
        "onTertiaryFixedVariant" to TokenColorReference("infoStrong", "#1C557D"),
    )
    val dark = mapOf(
        "primary" to TokenColorReference("accent", "#BD4F5D"),
        "onPrimary" to TokenColorReference("onAccent", "#FFFFFF"),
        "primaryContainer" to TokenColorReference("accentSubtleBg", "#2F1E21"),
        "onPrimaryContainer" to TokenColorReference("accentStrong", "#E0929C"),
        "inversePrimary" to TokenColorReference("accentHover", "#CB6371"),
        "secondary" to TokenColorReference("textSecondary", "#B7ABA6"),
        "onSecondary" to TokenColorReference("bg", "#191412"),
        "secondaryContainer" to TokenColorReference("surfaceMuted", "#342927"),
        "onSecondaryContainer" to TokenColorReference("text", "#F1EAE7"),
        "tertiary" to TokenColorReference("info", "#5FA3D6"),
        "onTertiary" to TokenColorReference("bg", "#191412"),
        "tertiaryContainer" to TokenColorReference("infoBg", "#16242F"),
        "onTertiaryContainer" to TokenColorReference("infoStrong", "#5FA3D6"),
        "background" to TokenColorReference("bg", "#191412"),
        "surface" to TokenColorReference("surface", "#221B19"),
        "surfaceVariant" to TokenColorReference("surfaceSubtle", "#2B2220"),
        "surfaceTint" to TokenColorReference("accent", "#BD4F5D"),
        "inverseSurface" to TokenColorReference("text", "#F1EAE7"),
        "inverseOnSurface" to TokenColorReference("bg", "#191412"),
        "outline" to TokenColorReference("border", "#4A3236"),
        "outlineVariant" to TokenColorReference("borderSubtle", "#332927"),
        "scrim" to TokenColorReference("bg", "#191412"),
        "onBackground" to TokenColorReference("text", "#F1EAE7"),
        "onSurface" to TokenColorReference("text", "#F1EAE7"),
        "onSurfaceVariant" to TokenColorReference("textSecondary", "#B7ABA6"),
        "error" to TokenColorReference("danger", "#E06A6A"),
        "onError" to TokenColorReference("onAccent", "#FFFFFF"),
        "errorContainer" to TokenColorReference("dangerBg", "#2C1A1A"),
        "onErrorContainer" to TokenColorReference("dangerStrong", "#E06A6A"),
        "surfaceBright" to TokenColorReference("surfaceMuted", "#342927"),
        "surfaceDim" to TokenColorReference("bg", "#191412"),
        "surfaceContainer" to TokenColorReference("surfaceSubtle", "#2B2220"),
        "surfaceContainerHigh" to TokenColorReference("surfaceMuted", "#342927"),
        "surfaceContainerHighest" to TokenColorReference("borderSubtle", "#332927"),
        "surfaceContainerLow" to TokenColorReference("surface", "#221B19"),
        "surfaceContainerLowest" to TokenColorReference("bg", "#191412"),
        "primaryFixed" to TokenColorReference("accentSubtleBg", "#2F1E21"),
        "primaryFixedDim" to TokenColorReference("accentSubtleBd", "#5A3338"),
        "onPrimaryFixed" to TokenColorReference("text", "#F1EAE7"),
        "onPrimaryFixedVariant" to TokenColorReference("accentStrong", "#E0929C"),
        "secondaryFixed" to TokenColorReference("surfaceMuted", "#342927"),
        "secondaryFixedDim" to TokenColorReference("border", "#4A3236"),
        "onSecondaryFixed" to TokenColorReference("text", "#F1EAE7"),
        "onSecondaryFixedVariant" to TokenColorReference("textSecondary", "#B7ABA6"),
        "tertiaryFixed" to TokenColorReference("infoBg", "#16242F"),
        "tertiaryFixedDim" to TokenColorReference("infoBd", "#294454"),
        "onTertiaryFixed" to TokenColorReference("text", "#F1EAE7"),
        "onTertiaryFixedVariant" to TokenColorReference("infoStrong", "#5FA3D6"),
    )
}

fun taskenLightColorScheme(): ColorScheme = TaskenMaterialColorTokens.light.toColorScheme(isDark = false)

fun taskenDarkColorScheme(): ColorScheme = TaskenMaterialColorTokens.dark.toColorScheme(isDark = true)

private fun Map<String, TokenColorReference>.toColorScheme(isDark: Boolean): ColorScheme {
    fun role(name: String) = getValue(name).hex.toComposeColor()
    val arguments = ColorSchemeArguments(
        primary = role("primary"),
        onPrimary = role("onPrimary"),
        primaryContainer = role("primaryContainer"),
        onPrimaryContainer = role("onPrimaryContainer"),
        secondary = role("secondary"),
        onSecondary = role("onSecondary"),
        secondaryContainer = role("secondaryContainer"),
        onSecondaryContainer = role("onSecondaryContainer"),
        tertiary = role("tertiary"),
        onTertiary = role("onTertiary"),
        tertiaryContainer = role("tertiaryContainer"),
        onTertiaryContainer = role("onTertiaryContainer"),
        background = role("background"),
        surface = role("surface"),
        surfaceVariant = role("surfaceVariant"),
        outline = role("outline"),
        onBackground = role("onBackground"),
        onSurface = role("onSurface"),
        onSurfaceVariant = role("onSurfaceVariant"),
        error = role("error"),
        errorContainer = role("errorContainer"),
    )
    return (if (isDark) arguments.dark() else arguments.light()).copy(
        inversePrimary = role("inversePrimary"),
        surfaceTint = role("surfaceTint"),
        inverseSurface = role("inverseSurface"),
        inverseOnSurface = role("inverseOnSurface"),
        outlineVariant = role("outlineVariant"),
        scrim = role("scrim"),
        onError = role("onError"),
        onErrorContainer = role("onErrorContainer"),
        surfaceBright = role("surfaceBright"),
        surfaceDim = role("surfaceDim"),
        surfaceContainer = role("surfaceContainer"),
        surfaceContainerHigh = role("surfaceContainerHigh"),
        surfaceContainerHighest = role("surfaceContainerHighest"),
        surfaceContainerLow = role("surfaceContainerLow"),
        surfaceContainerLowest = role("surfaceContainerLowest"),
        primaryFixed = role("primaryFixed"),
        primaryFixedDim = role("primaryFixedDim"),
        onPrimaryFixed = role("onPrimaryFixed"),
        onPrimaryFixedVariant = role("onPrimaryFixedVariant"),
        secondaryFixed = role("secondaryFixed"),
        secondaryFixedDim = role("secondaryFixedDim"),
        onSecondaryFixed = role("onSecondaryFixed"),
        onSecondaryFixedVariant = role("onSecondaryFixedVariant"),
        tertiaryFixed = role("tertiaryFixed"),
        tertiaryFixedDim = role("tertiaryFixedDim"),
        onTertiaryFixed = role("onTertiaryFixed"),
        onTertiaryFixedVariant = role("onTertiaryFixedVariant"),
    )
}

private data class ColorSchemeArguments(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val outline: Color,
    val onBackground: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val error: Color,
    val errorContainer: Color,
) {
    fun light() = lightColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        error = error,
        errorContainer = errorContainer,
        outline = outline,
    )

    fun dark() = darkColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        error = error,
        errorContainer = errorContainer,
        outline = outline,
    )
}

private fun String.toComposeColor(): Color {
    val rgb = removePrefix("#").toLong(16)
    return Color(0xFF000000 or rgb)
}
