/** @deprecated Import from workspace/domain-model/compat/timelineProjection instead */
export {
  v2TimelineItems,
  v2TimelineDependencies,
  timelineRangeItems,
  isTimelineCompleted,
  timelineThemeId,
  timelineItemHasSchedule,
  timelineItemLevel,
  timelineItemIsMilestone,
  timelineItemStatusLabel,
  timelineItemStatusValue,
  timelineItemDateSpan,
  timelineShiftItemDraft,
  timelineReparentItemDraft,
  timelineAddPlanDraft,
  legacyTimelineWorkspace,
  timelineSaveItemOperations,
  timelineCreatePlanNodeDraft,
  timelineResolveParentPlanNodeId,
  timelineAddDependencyOperations,
  timelineFindDependencyV2Id,
} from "../../workspace/domain-model/compat/timelineProjection";
