/** @deprecated Import from workspace/domain-model/types instead */
export type {
  ProjectState,
  Project,
  CaptureEntryState,
  CaptureEntry,
  TaskState,
  Task,
  WaitingState,
  Waiting,
  PlanNodeType,
  PlanNodeState,
  PlanNode,
  ScheduleOwnerType,
  Schedule,
  Note,
  Resource,
  KnowledgeNodeType,
  KnowledgeNode,
  EntityRefType,
  Reference,
  TaskDependency,
  PlanDependency,
  KnowledgeEdge,
  ChangeEvent,
  WorkspaceDomain as WorkspaceV2,
  WorkspaceDomain,
  DomainEntity as V2Entity,
  DomainEntity,
} from "../../workspace/domain-model/types";
