import {
  aiEntityBodyText,
  projectEntityForAi,
  summarizeAiExclusions,
} from "./aiMetadata.mjs";
import { markdownSignature } from "./canonicalMarkdown.mjs";

export const THEME_AI_PACK_SCHEMA = "tasken-ai-pack/v1";

export const THEME_AI_PACK_FILES = Object.freeze([
  Object.freeze({ key: "overview", name: "00 Theme Overview.md", title: "Theme Overview" }),
  Object.freeze({ key: "current_work", name: "01 Current Work.md", title: "Current Work" }),
  Object.freeze({ key: "decisions", name: "02 Decisions.md", title: "Decisions" }),
  Object.freeze({ key: "meetings", name: "03 Meetings.md", title: "Meetings" }),
  Object.freeze({ key: "procedures", name: "04 Procedures.md", title: "Procedures" }),
  Object.freeze({ key: "knowledge", name: "05 Knowledge.md", title: "Knowledge" }),
  Object.freeze({ key: "activity", name: "06 Activity.md", title: "Activity" }),
]);

const CURRENT_WORK_TYPES = new Set(["item", "task", "waiting", "plan_node", "status_update"]);
const TERMINAL_WORK_STATES = new Set(["done", "completed", "cancelled", "canceled", "archived"]);
const DECISION_KINDS = new Set(["decision"]);
const MEETING_KINDS = new Set(["meeting", "minutes", "meeting_note"]);
const PROCEDURE_KINDS = new Set(["procedure", "runbook", "sop"]);
const CONVERSATION_TYPES = new Set(["conversation", "chat_ref"]);
const ABSOLUTE_PATH = /^(?:[A-Za-z]:[\\/]|[\\/]{1,2})/;
const GENERATED_MARKER = "> Generated by Tasken — read-only projection. Edit the canonical Tasken entity, not this file.";
const DEFAULT_MAX_BODY_CHARS = 4_000;

function text(value) {
  return value == null ? "" : String(value);
}

function record(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function normalizedLines(value) {
  return text(value).replace(/\r\n?/g, "\n").trim();
}

function entityKey(type, id) {
  return `${text(type).trim()}:${text(id).trim()}`;
}

function compareCandidates(left, right) {
  return entityKey(left?.type, left?.entity?.id).localeCompare(entityKey(right?.type, right?.entity?.id));
}

function uniqueStrings(values) {
  return [...new Set(values.map((value) => text(value).trim()).filter(Boolean))].sort();
}

function safeRelativePath(value) {
  const candidate = text(value).trim().replace(/\\/g, "/");
  if (!candidate || ABSOLUTE_PATH.test(candidate)) return "";
  const segments = candidate.split("/");
  if (segments.some((segment) => segment === "..")) return "";
  return candidate.replace(/^\.\//, "");
}

function safeWebUrl(value) {
  const candidate = text(value).trim();
  if (!/^https:\/\//i.test(candidate)) return "";
  try {
    const parsed = new URL(candidate);
    if (parsed.username || parsed.password) return "";
    return parsed.toString();
  } catch {
    return "";
  }
}

function safeSourceRef(refValue) {
  const ref = record(refValue);
  const relativePath = safeRelativePath(ref.relative_path);
  const storageRootId = text(ref.storage_root_id).trim();
  const webCandidate = text(ref.web_url || (ref.kind === "url" ? ref.locator : "")).trim();
  const webUrl = safeWebUrl(webCandidate);
  if (webCandidate && !webUrl) return null;
  if (storageRootId && relativePath) {
    return {
      kind: text(ref.kind).trim() || "canonical_document",
      label: text(ref.title).trim() || relativePath,
      locator: `${storageRootId}:${relativePath}`,
    };
  }
  if (webUrl) {
    return {
      kind: text(ref.kind).trim() || "url",
      label: text(ref.title).trim() || webUrl,
      locator: webUrl,
    };
  }
  const locator = text(ref.locator).trim();
  if (!locator || ABSOLUTE_PATH.test(locator) || locator.split(/[\\/]/).includes("..")) return null;
  return {
    kind: text(ref.kind).trim() || "reference",
    label: text(ref.title).trim() || locator,
    locator,
  };
}

function canonicalRefsFrom(entity) {
  const properties = record(entity.properties_json);
  const binding = record(properties.canonical_markdown);
  const refs = [
    ...(Array.isArray(entity.canonical_refs) ? entity.canonical_refs : []),
    ...(entity.canonical_ref ? [entity.canonical_ref] : []),
  ];
  const rootId = text(binding.storage_root_id || binding.root_identity).trim();
  const relativePath = safeRelativePath(binding.relative_path || binding.file_name);
  if (rootId && relativePath) {
    refs.push({ kind: "canonical_document", storage_root_id: rootId, relative_path: relativePath });
  }
  return refs;
}

function sourceRefsFor(header, entity, publication) {
  const refs = [
    ...(Array.isArray(header?.source_refs) ? header.source_refs : []),
    ...canonicalRefsFrom(entity),
  ];
  if (publication?.published) {
    refs.push({
      kind: "conversation",
      title: publication.title || entity.title,
      storage_root_id: publication.storage_root_id,
      relative_path: publication.relative_path,
      web_url: publication.web_url,
      locator: publication.locator,
    });
  }
  const safe = refs.map(safeSourceRef).filter(Boolean);
  return [...new Map(safe.map((ref) => [`${ref.kind}|${ref.locator}`, ref])).values()]
    .sort((left, right) => `${left.kind}|${left.locator}`.localeCompare(`${right.kind}|${right.locator}`));
}

function isConversation(type, entity) {
  return CONVERSATION_TYPES.has(type)
    || (type === "resource" && text(entity.resource_scope).trim() === "chat_ref");
}

function withoutConversationBody(entity) {
  const { body_markdown: _body, body: _legacyBody, text: _text, description: _description, ...safe } = entity;
  return safe;
}

function themeMatches(candidate, themeId) {
  const entity = record(candidate.entity);
  const directThemeId = text(entity.project_id || entity.theme_id).trim();
  if (directThemeId) return directThemeId === themeId;
  if (candidate.relatedToTheme === true) return true;
  return text(candidate.relation?.themeId).trim() === themeId;
}

function exclusion(id, type, reason) {
  return { id: text(id).trim(), type: text(type).trim() || "unknown", reason };
}

function sectionFor(type, entity, conversation) {
  if (conversation) return "meetings";
  if (CURRENT_WORK_TYPES.has(type)) return "current_work";
  const kind = text(entity.node_type || entity.note_type || entity.kind || entity.type).trim().toLowerCase();
  if (DECISION_KINDS.has(kind)) return "decisions";
  if (MEETING_KINDS.has(kind)) return "meetings";
  if (PROCEDURE_KINDS.has(kind)) return "procedures";
  return "knowledge";
}

function isUnconfirmedSuggestion(type, entity) {
  const state = text(entity.status || entity.state || entity.proposal_status).trim().toLowerCase();
  if (type === "ai_proposal") return state !== "adopted" && state !== "accepted";
  return (state === "suggested" || state === "proposed") && entity.ai_authority !== "user_confirmed";
}

function renderSourceRef(ref) {
  if (/^https:\/\//i.test(ref.locator)) return `[${ref.label}](${ref.locator})`;
  return `\`${ref.locator}\``;
}

function renderEntry(entry) {
  const lines = [
    `## ${entry.header.title || `${entry.type}:${entry.header.id}`}`,
    `- Entity: \`${entry.type}:${entry.header.id}\` ([open](tasken://${encodeURIComponent(entry.type)}/${encodeURIComponent(entry.header.id)}))`,
    `- Freshness: ${entry.header.freshness} — ${entry.header.freshness_reason}`,
    `- Authority: ${entry.header.authority || "unknown"} — ${entry.header.authority_reason}`,
    `- Summary authority: ${entry.header.summary_authority || "unknown"}`,
    `- Source: ${entry.sourceRefs.length ? entry.sourceRefs.map(renderSourceRef).join(", ") : "—"}`,
  ];
  if (entry.header.superseded_by) {
    lines.push(`- Superseded by: \`${entry.header.superseded_by.type}:${entry.header.superseded_by.id}\``);
  }
  if (entry.header.summary) lines.push("", entry.header.summary);
  if (entry.body) lines.push("", entry.body);
  if (entry.conversationReference) lines.push("", "Conversation本文はこのPackへ複製せず、公開済みprojectionを参照します。");
  return lines.join("\n");
}

function renderFile(title, entries, emptyLabel = "対象なし") {
  return [
    `# ${title}`,
    "",
    GENERATED_MARKER,
    "",
    ...(entries.length ? entries.flatMap((entry, index) => [index ? "" : null, renderEntry(entry)].filter(Boolean)) : [`- ${emptyLabel}`]),
    "",
  ].join("\n");
}

function renderOverview(themeEntry, sectionCounts, excludedSummary) {
  const lines = [
    "# Theme Overview",
    "",
    GENERATED_MARKER,
    "",
  ];
  if (themeEntry) lines.push(renderEntry(themeEntry), "");
  else lines.push("- Theme本文はM365公開対象外です。", "");
  lines.push(
    "## Pack contents",
    ...THEME_AI_PACK_FILES.filter((file) => file.key !== "overview")
      .map((file) => `- ${file.name}: ${sectionCounts[file.key] || 0}件`),
    "",
    "## Excluded by policy",
    ...(excludedSummary.excluded_reasons.length
      ? excludedSummary.excluded_reasons.map((entry) => `- ${entry.type}: ${entry.reason}（${entry.count}件）`)
      : ["- 除外なし"]),
    "",
  );
  return lines.join("\n");
}

function safeActivityRef(refValue) {
  const ref = record(refValue);
  const type = text(ref.type).trim();
  const id = text(ref.id).trim();
  return type && id ? { type, id, relation: text(ref.relation).trim() } : null;
}

function renderActivityEvent(event) {
  const entityRef = safeActivityRef(event.entity_ref);
  const themeRef = record(event.theme_ref);
  const canonicalRefs = (Array.isArray(event.canonical_refs) ? event.canonical_refs : []).map(safeSourceRef).filter(Boolean);
  const sourceRefs = (Array.isArray(event.source_refs) ? event.source_refs : []).map((ref) => {
    const entitySource = safeActivityRef(ref);
    return entitySource ? { kind: "entity", label: `${entitySource.type}:${entitySource.id}`, locator: `${entitySource.type}:${entitySource.id}` } : safeSourceRef(ref);
  }).filter(Boolean);
  const relationRefs = (Array.isArray(event.relation_refs) ? event.relation_refs : []).map(safeActivityRef).filter(Boolean);
  const receipt = safeActivityRef(event.work_receipt_ref);
  return [
    `## ${text(event.local_date).trim()} ${text(event.local_time).trim()} · ${text(event.event_kind).trim() || "event"}`.trim(),
    entityRef ? `- Entity: ${text(event.entity_title).trim() || entityRef.id} \`${entityRef.type}:${entityRef.id}\` ([open](tasken://${encodeURIComponent(entityRef.type)}/${encodeURIComponent(entityRef.id)}))` : "- Entity: —",
    `- Theme: ${themeRef.kind === "theme" && themeRef.id ? `\`${themeRef.id}\`` : "none"}`,
    `- Canonical: ${canonicalRefs.length ? canonicalRefs.map(renderSourceRef).join(", ") : "—"}`,
    `- Source: ${sourceRefs.length ? sourceRefs.map(renderSourceRef).join(", ") : "—"}`,
    `- Relations: ${relationRefs.length ? relationRefs.map((ref) => `${ref.relation || "related_to"} \`${ref.type}:${ref.id}\``).join(", ") : "—"}`,
    `- Work receipt: ${receipt ? `\`${receipt.type}:${receipt.id}\`` : "—"}`,
    `- Summary: ${normalizedLines(event.summary) || "—"}`,
  ].join("\n");
}

function renderActivity(events) {
  return [
    "# Activity",
    "",
    GENERATED_MARKER,
    "",
    ...(events.length ? events.flatMap((event, index) => [index ? "" : null, renderActivityEvent(event)].filter(Boolean)) : ["- 対象なし"]),
    "",
  ].join("\n");
}

function mergeExclusionSummary(exclusions, activity) {
  const own = summarizeAiExclusions(exclusions);
  const merged = new Map();
  const add = (entry) => {
    const type = text(entry?.type).trim() || "activity";
    const reason = text(entry?.reason).trim() || "Activity projectionで除外されました。";
    const key = `${type}|${reason}`;
    const current = merged.get(key) || { type, reason, count: 0 };
    current.count += Math.max(0, Number(entry?.count) || 0);
    merged.set(key, current);
  };
  own.excluded_reasons.forEach(add);
  (Array.isArray(activity?.excluded_reasons) ? activity.excluded_reasons : []).forEach(add);
  return {
    excluded_count: own.excluded_count + Math.max(0, Number(activity?.excluded_count) || 0),
    excluded_reasons: [...merged.values()].sort((left, right) => `${left.type}|${left.reason}`.localeCompare(`${right.type}|${right.reason}`)),
  };
}

/**
 * Theme向けM365 AI Packの内容を決めるpure planner。
 * ファイルI/Oは行わず、Previewとwriterが同じ戻り値を使用する。
 */
export function buildThemeAiPackPlan({
  theme,
  candidates = [],
  activity = { events: [], excluded_count: 0, excluded_reasons: [] },
  workspaceDefault = undefined,
  generatedAt = new Date().toISOString(),
  sourceRevision = null,
  maxBodyChars = DEFAULT_MAX_BODY_CHARS,
} = {}) {
  const themeEntity = record(theme);
  const themeId = text(themeEntity.id).trim();
  if (!themeId) throw new Error("Theme AI PackにはTheme IDが必要です。");
  const bodyLimit = Math.max(0, Number(maxBodyChars) || DEFAULT_MAX_BODY_CHARS);
  const exclusions = [];
  const sections = { current_work: [], decisions: [], meetings: [], procedures: [], knowledge: [] };
  const includedKeys = new Set();
  const activityAllowedKeys = new Set();

  const project = (type, entity, publication = null) => {
    const conversation = isConversation(type, entity);
    const projectionEntity = conversation ? withoutConversationBody(entity) : entity;
    const result = projectEntityForAi(type, projectionEntity, { audience: "m365", theme: themeEntity, workspaceDefault });
    if (!result.included) {
      exclusions.push(result.exclusion);
      return null;
    }
    if (conversation && !publication?.published) {
      exclusions.push(exclusion(entity.id, type, "ConversationはAI Contextへ明示公開されていないため除外しました。"));
      return null;
    }
    if (conversation && text(publication?.storage_root_id).trim() !== `theme:${themeId}`) {
      exclusions.push(exclusion(entity.id, type, "Conversationは別のThemeへ公開済みです。旧公開を解除してから再公開してください。"));
      return null;
    }
    const hasPublishedConversationRef = Boolean(
      (text(publication?.storage_root_id).trim() && safeRelativePath(publication?.relative_path))
      || safeWebUrl(publication?.web_url),
    );
    if (conversation && !hasPublishedConversationRef) {
      exclusions.push(exclusion(entity.id, type, "公開済みConversationの安全な参照先がないため除外しました。"));
      return null;
    }
    const sourceRefs = sourceRefsFor(result.header, entity, publication);
    let body = conversation ? "" : normalizedLines(aiEntityBodyText(type, entity));
    if (result.header.freshness === "superseded" && body) {
      exclusions.push(exclusion(entity.id, type, "置き換え済みEntityの本文は除外しました。"));
      body = "";
    } else if (body.length > bodyLimit) {
      exclusions.push(exclusion(entity.id, type, `本文が${bodyLimit}文字を超えるため概要だけを含めました。`));
      body = "";
    }
    return {
      type,
      entity,
      header: result.header,
      body,
      sourceRefs,
      conversationReference: conversation,
    };
  };

  const themeEntry = project("theme", themeEntity);
  if (themeEntry) {
    includedKeys.add(entityKey("theme", themeId));
    activityAllowedKeys.add(entityKey("theme", themeId));
  }

  for (const candidateValue of [...candidates].sort(compareCandidates)) {
    const candidate = record(candidateValue);
    const type = text(candidate.type).trim();
    const entity = record(candidate.entity);
    const id = text(entity.id).trim();
    if (!type || !id) {
      exclusions.push(exclusion(id, type, "Entity typeまたはIDがないため除外しました。"));
      continue;
    }
    if (entity.deleted_at) {
      exclusions.push(exclusion(id, type, "削除済みEntityのため除外しました。"));
      continue;
    }
    if (!themeMatches(candidate, themeId)) {
      exclusions.push(exclusion(id, type, "このThemeへの所属または明示的な関係がないため除外しました。"));
      continue;
    }
    if (isUnconfirmedSuggestion(type, entity)) {
      exclusions.push(exclusion(id, type, "ユーザー未確認の提案はM365 Packへ公開しません。"));
      continue;
    }
    const entry = project(type, entity, record(candidate.publication));
    if (!entry) continue;
    activityAllowedKeys.add(entityKey(type, id));
    if (CURRENT_WORK_TYPES.has(type) && TERMINAL_WORK_STATES.has(text(entity.state || entity.status).trim().toLowerCase())) {
      exclusions.push(exclusion(id, type, "完了済みの作業はCurrent Workから除外しました。"));
      continue;
    }
    const section = sectionFor(type, entity, entry.conversationReference);
    sections[section].push(entry);
    includedKeys.add(entityKey(type, id));
  }

  const projectedActivity = [];
  for (const eventValue of [...(Array.isArray(activity?.events) ? activity.events : [])]
    .sort((left, right) => `${text(left?.occurred_at)}|${text(left?.id)}`.localeCompare(`${text(right?.occurred_at)}|${text(right?.id)}`))) {
    const event = record(eventValue);
    const ref = safeActivityRef(event.entity_ref);
    if (!ref || !activityAllowedKeys.has(entityKey(ref.type, ref.id))) continue;
    projectedActivity.push(event);
  }

  const excludedSummary = mergeExclusionSummary(exclusions, activity);
  const sectionCounts = {
    current_work: sections.current_work.length,
    decisions: sections.decisions.length,
    meetings: sections.meetings.length,
    procedures: sections.procedures.length,
    knowledge: sections.knowledge.length,
    activity: projectedActivity.length,
  };
  const contents = {
    overview: renderOverview(themeEntry, sectionCounts, excludedSummary),
    current_work: renderFile("Current Work", sections.current_work),
    decisions: renderFile("Decisions", sections.decisions),
    meetings: renderFile("Meetings", sections.meetings),
    procedures: renderFile("Procedures", sections.procedures),
    knowledge: renderFile("Knowledge", sections.knowledge),
    activity: renderActivity(projectedActivity),
  };
  const files = THEME_AI_PACK_FILES.map((definition) => {
    const entries = definition.key === "overview"
      ? (themeEntry ? [themeEntry] : [])
      : definition.key === "activity"
        ? projectedActivity
        : sections[definition.key];
    const includedEntityIds = definition.key === "activity"
      ? uniqueStrings(entries.map((entry) => entry?.entity_ref?.id))
      : uniqueStrings(entries.map((entry) => entry?.header?.id));
    const content = contents[definition.key];
    return {
      name: definition.name,
      content,
      content_hash: markdownSignature(content),
      includedEntityIds,
    };
  });
  const contentHash = markdownSignature(JSON.stringify(files.map((file) => ({
    name: file.name,
    content_hash: file.content_hash,
    includedEntityIds: file.includedEntityIds,
  }))));
  const includedEntityIds = uniqueStrings([
    ...(themeEntry ? [themeId] : []),
    ...Object.values(sections).flatMap((entries) => entries.map((entry) => entry.header.id)),
    ...projectedActivity.map((event) => event?.entity_ref?.id),
  ]);
  const freshnessWarnings = [
    ...(themeEntry ? [themeEntry] : []),
    ...Object.values(sections).flat(),
  ].filter((entry) => entry.header.freshness === "stale" || entry.header.freshness === "superseded")
    .map((entry) => ({
      kind: entry.header.freshness,
      type: entry.type,
      id: entry.header.id,
      title: entry.header.title,
      reason: entry.header.freshness_reason,
    }))
    .sort((left, right) => `${left.kind}|${left.type}|${left.id}`.localeCompare(`${right.kind}|${right.type}|${right.id}`));
  const preview = {
    files: files.map((file) => ({
      name: file.name,
      includedCount: file.includedEntityIds.length,
      characterCount: file.content.length,
    })),
    includedCount: includedEntityIds.length,
    excludedCount: excludedSummary.excluded_count,
    excludedReasons: excludedSummary.excluded_reasons,
    warnings: freshnessWarnings,
    totalCharacterCount: files.reduce((sum, file) => sum + file.content.length, 0),
  };
  const manifest = {
    schema: THEME_AI_PACK_SCHEMA,
    themeId,
    generatedAt: text(generatedAt).trim(),
    sourceRevision: sourceRevision == null ? null : text(sourceRevision),
    projection: "generated_read_only",
    audience: "m365",
    contentHash,
    files: files.map((file) => ({
      name: file.name,
      contentHash: file.content_hash,
      includedEntityIds: file.includedEntityIds,
    })),
    includedEntityIds,
    excludedCount: excludedSummary.excluded_count,
    excludedReasons: excludedSummary.excluded_reasons,
  };
  return {
    schema: THEME_AI_PACK_SCHEMA,
    theme_id: themeId,
    audience: "m365",
    generated_at: manifest.generatedAt,
    source_revision: manifest.sourceRevision,
    content_hash: contentHash,
    files,
    manifest,
    preview,
    included_entity_ids: includedEntityIds,
    excluded_count: excludedSummary.excluded_count,
    excluded_reasons: excludedSummary.excluded_reasons,
  };
}
